package banco;

/**
 * banco/conta_inval.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from Banco.idl Thursday, October 9, 2008 3:43:50 PM BRT
 */

public final class conta_inval extends org.omg.CORBA.UserException {
    private static final long serialVersionUID = 8674928798056568039L;
    public int c = (int) 0;

    public conta_inval() {
	super(conta_invalHelper.id());
    } // ctor

    public conta_inval(int _c) {
	super(conta_invalHelper.id());
	c = _c;
    } // ctor

    public conta_inval(String $reason, int _c) {
	super(conta_invalHelper.id() + "  " + $reason);
	c = _c;
    } // ctor

} // class conta_inval
