package banco;

/**
 * banco/moeda.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from Banco.idl Thursday, October 9, 2008 3:43:50 PM BRT
 */

public interface moeda {
    public static final String value = "R$";
}
