package banco;

/**
 * banco/saldo_insuf.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from Banco.idl Thursday, October 9, 2008 3:43:50 PM BRT
 */

public final class saldo_insuf extends org.omg.CORBA.UserException {
    private static final long serialVersionUID = 4395270712062065288L;
    public double saldo = (double) 0;

    public saldo_insuf() {
	super(saldo_insufHelper.id());
    } // ctor

    public saldo_insuf(double _saldo) {
	super(saldo_insufHelper.id());
	saldo = _saldo;
    } // ctor

    public saldo_insuf(String $reason, double _saldo) {
	super(saldo_insufHelper.id() + "  " + $reason);
	saldo = _saldo;
    } // ctor

} // class saldo_insuf
