package banco;

/**
 * banco/auto_atendimento.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Banco.idl Thursday, October 9, 2008 3:43:50 PM
 * BRT
 */

public interface auto_atendimento extends auto_atendimentoOperations, org.omg.CORBA.Object,
	org.omg.CORBA.portable.IDLEntity {
} // interface auto_atendimento
