package banco;

/**
 * banco/caixa_eletronicoOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Banco.idl Thursday, October 9, 2008 3:43:50 PM
 * BRT
 */

public interface caixa_eletronicoOperations extends banco.auto_atendimentoOperations {
    void saque(int c, double v) throws banco.conta_inval, banco.saldo_insuf;
} // interface caixa_eletronicoOperations
