package banco;

/**
 * banco/caixa_eletronico.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from Banco.idl Thursday, October 9, 2008 3:43:50 PM
 * BRT
 */

public interface caixa_eletronico extends caixa_eletronicoOperations, banco.auto_atendimento,
	org.omg.CORBA.portable.IDLEntity {
} // interface caixa_eletronico
